---
title: "Hoja de trabajo 4"
author: "Gustavo de León - 17085 | Andrés Urízar - 17632"
date: "19/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
# Ubicacion de archivos en computadoras
  #setwd("C:/Users/Gustavo/Desktop/SEPTIMO SEMESTRE/MINERIA/HDT4/laboratorio_05")
  setwd("C:/Users/alber/Documents/UVG/Septimo semestre/Mineria de Datos/Hoja-Trabajo_4/laboratorio_05")
```
```{r}
  test <- read.csv("test.csv", stringsAsFactors = FALSE)
  train <- read.csv("train.csv", stringsAsFactors = FALSE)
  trainImportantes <- train[c("LotArea","OverallCond","YearBuilt","YearRemodAdd","FullBath","TotRmsAbvGrd","KitchenAbvGr","GarageCars")]
  trainImportantes[is.na(trainImportantes)]<-0
```
```{r}
  porcentaje<-0.7
  set.seed(123)
  corte <- sample(nrow(trainImportantes),nrow(trainImportantes)*porcentaje)
  train<-trainImportantes[corte,]
  test<-trainImportantes[-corte,]
```
```{r}
fitLMPW<-lm(SalePrice~., data = train)
summary(fitLMPW)
```
```{r}
predL<-predict(fitLMPW, newdata = test)
head(predL)
length(predL)
```